name: Run G2Ray

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4  # نسخه ۴ از Node.js 20 استفاده نمی‌کند

      - name: Setup and Run
        env:
          PASS: ${{ secrets.MY_UUID }}
        run: |
          if [ -z "$PASS" ]; then
            PASS=$(curl -sk https://raw.githubusercontent.com/edrisranjbar/g2ray/main/uuid)
          fi
          PORT=$(( (RANDOM % 50000) + 10000 ))
          bash g2ray.sh "$PASS" "$PORT"
